In [2]:
import pandas as pd

In [29]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],columns=["a","b","c"],index=["w","x","y","z"])

In [30]:
df.head()

    a   b   c
w   1   2   3
x   4   5   6
y   7   8   9
z  10  11  12

In [14]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [20]:
df.describe()

         a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [22]:
df.shape

(3, 3)

In [23]:
df.nunique()

a    3
b    3
c    3
dtype: int64

In [25]:
df["a"].unique()

array([1, 4, 7], dtype=int64)

In [3]:
coffee= pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')

In [33]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [4]:
results=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv')

In [36]:
results.head()

     year    type discipline                     event                     as  ...  noc             team place   tied  medal
0  1912.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy  ...  FRA              NaN  17.0   True    NaN
1  1912.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy  ...  FRA   Jean Montariol   NaN  False    NaN
2  1920.0  Summer     Tennis    Singles, Men (Olympic)  Jean-François Blanchy  ...  FRA              NaN  32.0   True    NaN
3  1920.0  Summer     Tennis  Doubles, Mixed (Olympic)  Jean-François Blanchy  ...  FRA  Jeanne Vaussard   8.0   True    NaN
4  1920.0  Summer     Tennis    Doubles, Men (Olympic)  Jean-François Blanchy  ...  FRA  Jacques Brugnon   4.0  False    NaN

[5 rows x 11 columns]

In [5]:
bios= pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv')

In [38]:
results.sample(10)

          year    type                        discipline  ... place   tied   medal
239921  2018.0  Winter            Alpine Skiing (Skiing)  ...  13.0  False     NaN
72404   1904.0  Summer  Artistic Gymnastics (Gymnastics)  ...  99.0  False     NaN
202370  2000.0  Summer             Water Polo (Aquatics)  ...   9.0  False     NaN
253269  2012.0  Summer                           Sailing  ...  14.0  False     NaN
103542  1968.0  Summer               Swimming (Aquatics)  ...   5.0  False     NaN
41139   1972.0  Summer                           Fencing  ...  11.0  False     NaN
185794  2004.0  Summer                         Athletics  ...   6.0  False     NaN
114923  1932.0  Summer               Swimming (Aquatics)  ...   3.0  False  Bronze
121965  1952.0  Summer                     Weightlifting  ...   2.0  False  Silver
39863   1900.0  Summer                           Fencing  ...   1.0  False    Gold

[10 rows x 11 columns]

In [39]:
# loc and iloc

In [45]:
coffee.loc[5:12,["Day","Units Sold"]]

          Day  Units Sold
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45

In [46]:
#at and iat

In [48]:
coffee.at[0,"Units Sold"]

25

In [49]:
coffee.iat[0,0] #cant load multiple items using this

'Monday'

In [50]:
coffee.iloc[0,0]

'Monday'

In [51]:
coffee.sort_values("Units Sold", ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [57]:
'''for index, row in coffee.iterrows():
    print(index)
    print(row["Units Sold"])
    print("\n\n\n")'''

'for index, row in coffee.iterrows():\n    print(index)\n    print(row["Units Sold"])\n    print("\n\n\n")'

In [59]:
bios.loc[bios["height_cm"]>215,['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [6]:
bios[(bios["height_cm"]>215) & (bios["born_country"]=="USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [12]:
bios[bios["name"].str.contains('sami$', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19255,19391,Toshio Usami,1908-02-22,NaN,NaN,NaN,Japan,NaN,NaN,1991-06-01
36342,36629,Ali Abdel Sami,1936-01-06,NaN,NaN,NaN,Egypt,NaN,NaN,NaN
36343,36630,Mohamed Abdel Sami,1936-01-01,NaN,NaN,NaN,United Arab Republic,NaN,NaN,NaN
55616,56012,Deven Govindasami,1963-05-05,NaN,NaN,NaN,India,163.0,56.0,NaN
72110,72656,Akio Usami,1943-05-31,Tsubame,Niigata,JPN,Japan,168.0,59.0,NaN
72500,73052,Souliyasak Ketkeolatsami,1971-01-24,NaN,NaN,NaN,Lao People's Democratic Republic,NaN,NaN,NaN
102113,103048,Tajeddine Sami,1982-06-10,NaN,NaN,NaN,Morocco,176.0,68.0,NaN
113025,114314,Daisuke Usami,1979-03-29,Yokote,Akita,JPN,Japan,183.0,83.0,NaN
119161,120947,Takashi Usami,1992-05-06,Nagaokakyo,Kyoto,JPN,Japan,178.0,68.0,NaN
124073,126339,Pajtim Kasami,1992-06-02,Struga,Struga,MKD,Switzerland,171.0,85.0,NaN